name: IoC Apply CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/infrastructure.yml'
      - 'terraform/**'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.3.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::775254019113:role/github-role
          aws-region: eu-central-1

      - name: Terraform Init
        id: init
        working-directory: terraform
        run: |
          terraform init

      - name: Terraform Apply
        id: apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var aws_access_key=${{ env.AWS_ACCESS_KEY_ID }} \
            -var aws_secret_key=${{ env.AWS_SECRET_ACCESS_KEY }} \
            -var aws_session_token=${{ env.AWS_SESSION_TOKEN }} \
            -var aws_region=${{ env.AWS_REGION }} \
            -no-color
